name: Build

on:
  workflow_dispatch:
    inputs:
      useCache:
        description: Use GHA cache
        type: boolean
        required: false
        default: true
  push:
    branches:
      - "valhalla_python"
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - "valhalla_python"
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: manylinux_2_28_${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: x86_64
            runner: ubuntu-latest
          - platform: aarch64
            runner: ubuntu-latest-arm

    env:
      POLICY: manylinux_2_28
      PLATFORM: ${{ matrix.platform }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore cache
        if: github.event_name != 'workflow_dispatch' || fromJSON(github.event.inputs.useCache)
        uses: actions/cache/restore@v4
        with:
          path: .buildx-cache-manylinux_2_28_${{ matrix.platform }}/
          key: buildx-cache-manylinux_2_28_${{ matrix.platform }}-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-manylinux_2_28_${{ matrix.platform }}-

      - name: Get branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        run: ./build.sh

      - name: Save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .buildx-cache-manylinux_2_28_${{ matrix.platform }}/
          key: buildx-cache-manylinux_2_28_${{ matrix.platform }}-${{ hashFiles('docker/**') }}

      - name: Push image
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker tag quay.io/pypa/manylinux_2_28_${{ matrix.platform }}:${{ github.sha }} ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_${{ matrix.platform }}_${{ env.BRANCH }}
          docker push ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_${{ matrix.platform }}_${{ env.BRANCH }}
          docker image rm quay.io/pypa/manylinux_2_28_${{ matrix.platform }}:${{ github.sha }}

  create_manifest:
    name: Create multi-arch manifest
    runs-on: ubuntu-latest
    needs: build_manylinux
    if: github.event_name == 'push'

    steps:
      - name: Get branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Create and push manifest
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker manifest create ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_${{ env.BRANCH }} \
            --amend ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_x86_64_${{ env.BRANCH }} \
            --amend ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_aarch64_${{ env.BRANCH }}
          docker manifest push ghcr.io/${{ env.REPO_LOWERCASE }}:2_28_${{ env.BRANCH }}
